# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeSample_ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactNativeSample_ios
  pod 'Firebase/Core', '3.11.0'
  pod 'Firebase/Auth', '3.11.0'
  pod 'GoogleSignIn', '4.0.1'
  pod 'GoogleTagManager', '~> 5.0'

  target 'ReactNativeSample_ios-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactNativeSample_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
